import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import localFont from 'next/font/local'
import Script from 'next/script'

const neueMachina = localFont({
  src: [
    {
      path: './fonts/neue-machina/NeueMachina-Ultralight.woff2',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Ultrabold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/neue-machina/NeueMachina-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-neue-machina',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const cookieStore = await cookies()
const themeObj = cookieStore.get('theme')
const theme = themeObj?.value || 'light'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={neueMachina.variable} data-theme={theme}>
      <Script
        id="iubenda-cookie-banner"
        src="https://embeds.iubenda.com/widgets/8e61c31e-40b5-4ac2-a703-0e4c719f3d48.js"
        strategy="afterInteractive"
      />
      <body >{children}</body>
    </html>
  );
}
